apiVersion: v1
kind: Pod
metadata:
  name: dragonflyapp
  labels:
    app: dragonflyapp
spec:
  containers:
  - name: dragonflyapp
    image: manojreddyaleti/my-testing-app:JenkinsBuildNo
    ports:
      - containerPort: 8085
  imagePullSecrets:
  - name: dragonflyapp